config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :articles
  get "history", to:"searches#get_history"
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :body, presence: true, length: { minimum: 10, maximum: 500 }
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  validates :query, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :searches, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    ip = if request.headers["X-Forwarded-For"].present?
        request.headers["X-Forwarded-For"].split(",").first.strip
      else
        request.remote_ip
      end
    current_user ||= User.find_or_create_by(ip: ip)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    if params[:query].present?
      @articles = Article.where("title LIKE ? OR body LIKE ?", "%#{ActiveRecord::Base.sanitize_sql_like(params[:query])}%", "%#{ActiveRecord::Base.sanitize_sql_like(params[:query])}%")
    else
      @articles = Article.all
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def index
    @searches = Search.group(:query).order('count_all DESC').count
  end

  def get_history
    @searches = current_user.searches.order(created_at: :desc)
  end

  def create
    SaveSearchJob.perform_async(search_params.to_h, current_user.id)
  end
end

private 

def search_params
  params.require(:search).permit(:query)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/articles/_articles.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title" ><%=link_to article.title, article_path(article), class:"text-success"%></h5>
            <p class="card-text"><%= article.body %></p>
          </div>
          <div class="card-footer text-muted">
            <small>
              Created <%=time_ago_in_words(article.created_at)%> ago <br>
              Updated <%=time_ago_in_words(article.updated_at)%> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/articles/index.html.erb
<div class="row justify-content-md-center mr-0">
  <div class="col-4 mt-4"> 
    <%= form_with(url: articles_path, method: :get, data: {controller: "search-form", turbo_frame: "articles_turbo", turbo_action: "advance" }) do |form| %>
     <form class="form-inline my-2 my-lg-0">
         <%= form.text_field :query, id:"searchInput", class: "form-control mr-sm-2", placeholder: "What do you think about?", data: { action: "input->search-form#search" } %>
     </form>
    <% end %>
  </div>
</div>


<%= turbo_frame_tag "articles_turbo" do %>
  <%= render "articles" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; Search Box</small>
  </div>
</footer>

app/views/layouts/_message.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name=="notice" ? "success" : "danger"%> alert-dismissible fade show" role="alert">
      <%= msg %>  
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:black;">
  <%=link_to "Search Box", root_path, class:"navbar-brand", id:"logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
         <%=link_to "Search History", history_path, class:"nav-link"%>
      </li>
      
      <li class="nav-item active">
         <%=link_to "Analytics & Trends", searches_path, class:"nav-link"%>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchBox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
    <link rel="stylesheet" href="/bootstrap-4-4-1/css/bootstrap.css" >
    <link rel="stylesheet" href="../app/assets/stylesheets/custom.css">
    <script src="/jquery/jquery-3-4-1.js"></script>
    <script src="/bootstrap-4-4-1/js/bootstrap.js"></script>
  </head>

  <body class="d-flex flex-column">
  
    <%= render 'layouts/navigation' %>
    <div id="page-content">
    <%= render 'layouts/message' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/searches/_searches.html.erb
<div class="container">
  <% @searches.each do |search| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title text-success"><%= search.query %></h5>
          </div>
          <div class="card-footer text-muted">
            <small>
              Created <%=time_ago_in_words(search.created_at)%> ago <br>
              Updated <%=time_ago_in_words(search.updated_at)%> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/searches/get_history.html.erb
<h1 class="text-center mt-4">Listing all Histories</h1>
<%= render "searches" %>

app/views/searches/index.html.erb
<h1 class="text-center mt-4">Analytics & Trends</h1>
<div class="container">
  <% @searches.each do |query, count| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title text-success"><%= query %></h5>
          </div>
          <div class="card-footer text-muted">
            <large>
              Searched <%= count %> times
            </large>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>